Repository kompics/kompact, pull requests merged in 2021-01, with the labels that each got.

#124 Bytes version upgrade to 1.0
  Cargo.lock
  core/Cargo.toml
  core/src/component/lifecycle.rs
  core/src/messaging/serialised.rs
  core/src/net/buffers/chunk_lease.rs
  core/src/net/buffers/chunk_ref.rs
  core/src/net/buffers/encode_buffer.rs
  core/src/net/frames.rs
  core/src/net/network_channel.rs
  core/src/serialisation/protobuf_serialisers.rs
  feature-tests/protobuf-test/Cargo.toml
  rustfmt.toml
Labels: update

#129 Resolving NetMessage Forwarding issues
  .github/workflows/main.yml
  .travis.yml
  Cargo.lock
  Dockerfile
  ci-preflight.sh
  core/src/net/buffers/chunk_lease.rs
  core/tests/dispatch_integration_tests.rs
  feature-tests/protobuf-test/src/messages/example.rs
  travis_install_protobuf.sh
Labels: bug

#126 Ask API
  .github/workflows/main.yml
  core/src/actors/refs.rs
  core/src/component/definition.rs
  core/src/messaging/framing.rs
  core/src/utils.rs
  core/src/utils/ask.rs
  core/src/utils/erased.rs
  core/src/utils/iter_extras.rs
  core/src/utils/macros.rs
  core/src/utils/mod.rs
  docs/examples/src/bin/counters.rs
  docs/examples/src/bin/counters_channel_pool.rs
  docs/examples/src/bin/counters_pool.rs
  docs/examples/src/bin/dns_resolver.rs
  docs/examples/src/bin/workers.rs
  docs/examples/src/bin/workers_sender.rs
  docs/src/introduction/state.md
  docs/src/local/communication/ask.md
  docs/src/local/communication/senders.md
  rustfmt.toml
Labels: needs-docs
